# FQDN of the final cluster is {name}-{cluster.name}.<basedomain>...
# Name of the final managed cluster is {name}-{clusters[].name}
# - t1-aws0
# - t1-aws1
# - t1-azure0
# Name of the cluster sets: {name}-{clusterSets[].name}
# - t1-clusterset1
# - t1-clusterset2
name: tenant1
clusters:
- name: aws0
  type: aws
  imageName: img4.8.25-x86-64-appsub
  region: eu-west-1
  network:
    clusterCidr: 10.128.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.30.0.0/16
- name: aws1
  type: aws
  region: ap-southeast-1
  imageName: img4.8.25-x86-64-appsub
  network:
    clusterCidr: 10.128.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.30.0.0/16
- name: azure0
  type: azure
  imageName: img4.8.25-x86-64-appsub
  region: australiaeast
  network:
    clusterCidr: 10.140.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.33.0.0/16
clusterSets:
- name: t1-clusterset
  submariner: true
  clusters:
  - aws0
  - aws1
  - azure0

