# FQDN of the final cluster is {name}-{cluster.name}.<basedomain>...
# Name of the final managed cluster is {name}-{clusters[].name}
# - t2-aws0
# - t2-aws1
# - t2-azure0
# Name of the cluster sets: {name}-{clusterSets[].name}
# - t2-clusterset1
# - t2-clusterset2
name: tenant2
clusters:
- name: aws0 
  type: aws
  imageName: img4.8.25-x86-64-appsub
  region: eu-west-2
  network:
    clusterCidr: 10.128.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.30.0.0/16
- name: aws1 
  type: aws
  region: ap-southeast-2
  imageName: img4.8.25-x86-64-appsub
  network:
    clusterCidr: 10.128.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.30.0.0/16
- name: azure0
  type: azure
  imageName: img4.8.25-x86-64-appsub
  region: australiaeast
  network:
    clusterCidr: 10.140.0.0/14
    machineCidr: 10.0.0.0/16
    serviceCidr: 172.33.0.0/16
clusterSets:
- name: clusterset1
  submariner: true
  clusters:
  - aws0
  - aws1
- name: clusterset2
  submariner: false
  clusters:
  - azure0

