apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t1-apps
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    gitops.tier.layer: applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/rampadc/platform-config.git'
    path: tenants/t1/apps/appset-test
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true