---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant1-wait0
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  generators:
  - list:
      elements:
      - cluster: random-value
        url: https://1.2.3.4
  template:
    # Create an ArgoCD app for an AWS cluster build
    metadata:
      name: 't1-wait0'
      labels:
        gitops.tier.layer: applications
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      destination:
        namespace: openshift-gitops
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: 'https://github.com/otp-demo/otp-gitops-apps'
        targetRevision: 'master'
        path: wait
        helm:
          # Something to do with ApplicationSet templating here
          values: |
            enableNamespace: true